export interface Group {
  id?: number,
  name: string,
  description: string,
  employeeEmployeeInfo: number,
  employeeContactInfo: number,
  employeePersonalInfo: number,
  employeeAgentCertificates: number,
  employeeSystemAccessInformation: number,
  employeeUserGroup: number,
  employeeDocuments: number,
  employeeStatus: number,
  company: number,
  contacts: number,
  rfp: number,
  jobs: number,
  tasks: number,
  reports: number,
  referenceLinks: number,
  referenceDocuments: number,
  userGroup: number,
  masters: number,
  isActive: boolean
}