export interface Task {
  id?: number,
  assignedDate: Date,
  idAssignedTo: number,
  idAssignedBy: number,
  assignedBy:any,
  assignedTo:any,
  idTaskType: number,
  completeBy: any,
  idTaskStatus: number,
  generalNotes: string,
  idJobApplication: number,
  idWorkPermitType: number,
  idJob: number,
  idRfp: number,
  idContact: number,
  idCompany: number,
  idExaminer:number,
  jobNumber: string,
  rfpNumber: string,
  contactName: string,
  companyName: string,
  jobBillingType:number,
  idJobFeeSchedule:number,
  idRfpJobType:number,
  serviceQuantity:string,
  documentsToDelete:any,
  idJobDocuments:any,
}

export interface TaskJobDTO {
  id: number,
  idJob: number,
  assigned: Date,
  idAssignedTo: number,
  assignedTo: string,
  idAssignedBy: number,
  assignedBy: string,
  completeBy: any,
  idTaskStatus: number,
  statusDescription: string,
  generalNotes: string,
  idJobApplication: string,
  jobApplication: string,
  idWorkPermitType: number,
  workPermitType: string,
  progressCompletionNote: string,
  idTaskType: number,
  taskType: string,
  taskStatusName: string,
  badgeClass: string,
  startDate: Date,
  taskFor: string,
  idRfp: number,
  idContact: number,
  idCompany: number,
  idJobStatus: number,
  jobNumber: string,
  rfpNumber: string,
  contactName: string,
  companyName: string,
}


export interface ProgressionNotes {
  id: number,
  idJob: number,
  idRfp: number,
  idCompany: number,
  idContact: number,
  idTask: number,
  notes: string,
  idJobViolation:number
}

export interface FilterTask {
  isJob: boolean,
  isCompany: boolean,
  isContact: boolean,
  isRfp: boolean,
  idBorough: number,
  houseNumber: string,
  street: string,
  idTaskType: number,
  idTaskStatus: number,
  idAssignedBy: number,
  idAssignedTo: number,
  assignedFromDate: Date,
  assignedToDate: Date,
  completedFromDate: Date,
  completedToDate: Date,
  closedFromDate: Date,
  closedToDate: Date,
  idJob: number,
  idRfp: number,
  idCompany: number,
  idContact: number,
  idTask: number,
}


export interface Reminder {
  id: number,
  idTask: number,
  remindmeIn: number,
  reminderDate: Date,
  task: string,
  lastModifiedDate: Date,
  lastModifiedBy: string,
  lastModified: string
}

export enum TaskScope {
  "Scope Billing" = 1,
  "Other Billable Service" = 2,
}